import {IconProp} from '@fortawesome/fontawesome-svg-core';
import {
  faHouseChimney,
  faUtensils,
  faLightbulb,
  faCarSide,
  faPerson,
  faTicket,
  faPiggyBank,
  faMoneyBillTrendUp,
  faCreditCard,
  faHandHoldingDollar,
  faHeart,
  faChartPie,
  faCircle,
  faChevronLeft,
  faChevronRight,
  faPenToSquare,
  faPlus,
  faCheck,
  faCamera,
  faChevronDown,
} from '@fortawesome/free-solid-svg-icons';

export const icons: Record<string, IconProp> = {
  houseChimney: faHouseChimney,
  utensils: faUtensils,
  carSide: faCarSide,
  lightbulb: faLightbulb,
  handHoldingDollar: faHandHoldingDollar,
  person: faPerson,
  ticket: faTicket,
  piggyBank: faPiggyBank,
  moneyBillTrendUp: faMoneyBillTrendUp,
  creditCard: faCreditCard,
  heart: faHeart,
  chartPie: faChartPie,
  circle: faCircle,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  chevronDown: faChevronDown,
  penToSquare: faPenToSquare,
  plus: faPlus,
  check: faCheck,
  camera: faCamera,
};
